name: Main Branch Build

on:
  push:
    branches:
      - main

env:
  CONFIGURATION: Release
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET and restore
      uses: ./.github/actions/setup-dotnet
      
    - name: Build (Release)
      run: dotnet build --no-restore --configuration ${{ env.CONFIGURATION }} /p:AssemblyVersion=${{ github.run_number }} /p:ProductVersion=${{ github.run_number }}
  
  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET and restore
      uses: ./.github/actions/setup-dotnet
      
    - name: Build (Debug for coverage)
      run: dotnet build --no-restore --configuration Debug
      
    - name: Run tests with coverage
      uses: ./.github/actions/test-with-coverage
      with:
        codecov-token: ${{ secrets.CODECOV_TOKEN }}
